---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudflare-release
  namespace: cloudflare
spec:
  interval: 1m
  chart:
    spec:
      chart: cloudflare-tunnel # Nom du chart
      version: 0.3.2  # Version du chart
      sourceRef:
        kind: HelmRepository
        name: cloudflare-repository
        namespace: cloudflare
  values:
    cloudflare:
      tunnelName: "kubernetes-bytedragon-tech"
      tunnelId: "e2ce076e-6567-4837-ba6b-fc9a6de53032"
      secretName: cloudflare-tunnel-credentials
      ingress:
        - hostname: "*.bytedragon.tech"
          service: "https://ingress-nginx-release-controller.ingress-nginx.svc.cluster.local:443"
          originRequest:
            noTLSVerify: true
    resources:
      limits:
        cpu: "100m"
        memory: "128Mi"
      requests:
        cpu: "100m"
        memory: "128Mi"
    replicaCount: 2
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubernetes-sigs-release
  namespace: cloudflare
spec:
  interval: 1m
  chart:
    spec:
      chart: external-dns # Nom du chart
      version: 0.17.0  # Version du chart
      sourceRef:
        kind: HelmRepository
        name: kubernetes-sigs-repository
        namespace: cloudflare
  values:
    env:
    - name: CF_API_TOKEN
      valueFrom:
        secretKeyRef:
          key: apiKey
          name: cloudflare-api-key
    policy: sync
    provider:
      name: cloudflare
    sources:
    - ingress