---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-secret
  namespace: cloudflare
spec:
  encryptedData:
    apiKey: AgABEYJCqCq42dOPUanI/bNDPfPNg0Ux1Om2kiIRRzErydp3PiJrqxxMKSVSI8hw8uzku5iP7LG0WCiQQUtXswG6QLItdv6Mr2wrLm/E+QPVrvSwR9PN1jgvH+TLVCHg8eNGytq1J6bRlG9YPFN3s02NkcCKj+Ry+6LCo6OjK6rpB2OtGRNnitggp0WANfEGxPKCCAYLF1msX3r2cCnbxkwg1EBpUSMGULMNLJgV3WcvVZIzN5ar41tq0p7CjutX/iiMz+Xf1DKd6JJYO58vQOspZDshxFlm4wG9mV4LJmcn+Q+rQOS1bL3BLK4faujoelpx+g4JtbuAlGqVVmO9mlkrzWNmEdpjerknjHvWEVMdsfN4iemVTAgX3G7jpxdasZh9whV3gi7dI/mCDBlw7a5UorPCjxUp4OjLkNd5V0V9j4Yvv0oXozdgY06ZWMSRymVNLdHoP1son7CfrdaAs/U/hmKlK2Nf/paZYgXdmPuuL6kNPfC4YZSper0d5fN8dkq46+G9Nc3xcHt+OHFjJrIYaw/zdWRB799cLKc1TfgBuBKBlIb6XjaQqAhdCa1zUji4JotOhve0tMyzMAAIyEbVYT7gw0g1WJz5+2lPjrddaKl+TXxlTQ6f3ooGVoMoUGRKXIxUSS/4mNZDv+huMFuDkfyOcuZSZZGxkEPjel1oOTZp4Zarj094fwbZE+sNJKo7sZMuwTjRZ3IqTh45Ps0c8n9UFE2AfdoTdAlPdBM+pLQE6a/A4UJl
    email: AgCi4qzFBmDKlvq4TdZHkxHolpMI+TrPn2GXQOxCcs1YGGHwW7JfOgLu6c7tplgc3D/BYZ3PwALozuTvqJUlLtPFc/B/XNfiV8nD9h3k6OEgVavSryZtWE63Wp1kQmEVnQAbRal8dEOhgibvHsaPmo7L4zyTyEIExbrBg0d+IlwmWsshyMtcyWB4LDfqeFrjsFGz67I0rAq02RqLcYlJf2jHQ5QOq+aOqyQPonQya0EGnj3czTIgOeyP2BlgtQapTx5ADk2zJH6nMrgK740AzT6i0AHAftWLKSFKw2lMA0IsFFEekRdMA++ffX5x8MBCUCEnHqU8Lc3rojdNFEEJcVHXVVtML+6qqNZycfDTpm7lnAY4BUbL1aBDjCfu+WxRp9TBRJzm5cJYH5aBvNHxhVOOzb25wcM+imhMjC17zzXvSovzJuOFbX5LtgKGDTW0oeRURv6PffzBGtgTG6jsELkjffuZeTlfML8/gr8g0EeLpN+gL6l0gDXh86PHHealQvb0fP1AlcA5YiqHH+2ek6VmtNBr9EbfyfujHJX7JYrbfXRjsQ9r5GiOVX3XX7ASJvwo0J6ukdZ4Or3pylFBWyj9IBSbNTd7xkBaTmDhsfnTOkY1s7KtSTiJFIhl1m2NDP09r8r7Rxf5NhDqSSxOxeipJoAnAk685EqHJ2MeqrjWqEXMMFRUkA1elDNkIjqXhzrFyVYAR99tHDFchj7cKdDpm5rdkelzYdKihdw7u5Ji0A==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-secret
      namespace: cloudflare
