---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authentik-postgres-credentials
  namespace: authentik
spec:
  encryptedData:
    password: AgBLVqkcezbp20Ww+J6Y73dLIrlr6iIEhNHe8uyniam8yNSFWiCQoFc9Il2G8Oloag8q2W1JKFkZ3vHTTHprqpMe7eH+Tt+LOpLPvkKC7K3VvyYUfRo9rHpjfe3NnIzOEVbIg61zaIelc3GJ3kEt4Ca/a65j6gkb8BQZ0X0+LHBfJ+Use0UWrJ4WkSx6zbIQ5AUOlC+vzJSyC+odwmlzLyTAhN3gwb9wivRE0eh6+IV4GT+uJDBUP9I4szgLUKztZn5FLg2w3AgR6d8yCoDVoYol+w66kuJGURsdwf/w+kbax4VQN0ShREFFQNpRdiEEFgQ5YuRqfS+iqzBKtZSQ85IVt9A7A4e5x1TPk9TG7cbB9JvOdJGj+UGJCaCRxvjFNfQ9VR9godWrvtAzV4lvqSOBn0072bu6IO9a7sODYqnK/VWb5NdNQRA7X6YTsttVURiNGB5tSbl08v71xmoSYb3QOxLr3FbFzSMPP2N3K1F216o15G2hlyuM24nPfYQ9d+ioLGpXo2HxEcW1uZyTgAgu0vZNb+AIL6xvCKAVyxxwS4770AIYsiJFBF4c1xyeTsBOsqt8++xuu8W0psHGOQFw8xYr+rr06BNjsffrknAUsSxhP1xWxog+zBxj1ZP9QpSFk3vrNsi5b8Zff5XGW0TFtXyb6jW8RR8aseYxFXujI7zDlNxB6RsiqpzloGNS8GmF5ZjXZ0atK69Hew/NBXBQRMo=
    username: AgAHbYebRGYOrbBpP5TnWPea21BwdwJNPSdOOqxcC+Vaqj+tfTmhQ1tYY4c1CAcScH8pVNp6QclgJ19+TiJ5TypwMcQ1xe1bER3to99dv2IWLrXyVMw1iP9B5BGGt59m3HQ+rrNj9s287OZnJhlER4McHgTEaGKjsjeNYly0ciCF1yBvhSMC7f+I/J6JWkpLX3bwAF6XEct7klo+NHQ7kLr0vp6T/1UNEfZL/p6R14S9hopckpBp2pe/7h7FXL/GybZYVZ3WA/W5tNIfHVoW6g6CJxiibx9Y5krwspbiBBkIMoyYsTtoQT3pxuHTmeNrYFTqNKhMNKvFoRBkgnNPSrzx6BUFUtFLQGQBTd+Fp+yJoTq2vGN9wbooo1IlCTv7YGft7dQDfZY9g/B4tb4az0Kk0/tAitlZdmJlMLLt8iIEW4JK+K80EkR28rjLSviDdacyZOiL67PN4nMLY7pxMA5U/xhT9id9eIx0iKqmtmU/e66JF5IWAI4Rq4GhUfm3fkvoxzbXvtktyNWkV/t2RMteqCrK3Q3yxAfibnnFSgO/8K6El94KozPU3eqdgBRcUodDWnRcoMZrnh6s7IsIMaXFt8x5bFfsBq2dv41YOpj75x7zCG95jl38ULXgkOj5tMYUV6pobjP6PX4bIJ+FfD2VL84R7MPoxsde20YlzUeKiSAFV+LxQR7TSkBzyRIiJ+kNnEx8RK0ZiCw=
  template:
    metadata:
      creationTimestamp: null
      name: authentik-postgres-credentials
      namespace: authentik
