---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authentik-postgres-credentials
  namespace: authentik
spec:
  encryptedData:
    password: AgCQ+hcDkdyNnG0AaLUrCo5YaqNGb/JhzwJjbPtfaQrnFPRr+V0Y/RykwLfG5a9k0it2KxVb4xHl1X6wQNvrLMLjiZoxdAXvCIZ2Z/TW0XL4CYlK71obJlEDRIQPu4OkjroT5jEM+afLQKB302f13t7KNBf4QLBsgGdHS7Z21TV4u1QVAq/hIZBf6DFClyueCUjDBXf4ulgxkgCpuDVuhKCnGXGayppZQ3clieVZv7vR2/+uzvx+J1jRQCZuqs98D+a8yFP5H06A0GiJhEhSUB3kUA0G7qTCyXK4xl+hYZeiYPEMe7c8Y9j5jC1PTTNTPHH3HJsg/iNQatU0wqCVZc1td9lyxsUyJ/ljuxCcTi8e5DTCxpZiaMGPRT/pAiokJ1H1AY/IOmf50IAUVU+zRdSCV3ySySe+PRkvSIxkODU2jk6DTRF+xM843LOTX6l+onBcVqrlieX34llazFJAdDbtVlLzTQ0scyND0l4uUMlPXnmRnk9BddicSFnvUroBsA+5NUUjoBd1DZoM6ApatelfGemwXsT0jo6RHdMboUxzcsOQFt/52VuN87Yq4pQ0PDfA70hmHarwt92c6839oU8nrnfuH7ykSReWMA8NPdyEML3ozygm4OZQY4+HSr2yfNzllXbH/fG/2Ge/fsrfluOkrryTmSnq1b4oTy9Zv095CY9TKL7NFp+1X4pQNZT4lgbpNxpUeHhhxlxAGhyhTg+8dUgWnQ==
    username: AgAaWZ1sJq7dTUJlPf4TFU1pSygwndZ0E9RxzGzAk5/Q+ms0nVelIfuY0XUshq4DqFw4ykGvkES6GmBDjvLeZ06jit+5AeFpqdEskDjM9055p7gK4XXTK2vLtHaa/L04miG4ublrFAjRb4AR16D1b/aErw3fsE7f2fBeCG0uPvAdnKSizdcs1xHE/zeld5xulNMshS0SZvQ6AyMRnmV6nb5moMDyergVUbOX8BWOsGBHc4GlHT2jK7+n065fpsP1wedhrlGGtZE7nrWvK/JimuV9BeCpH1VhQAvR/Zv+ub3fK55lVkG9BXkSjxr5wii7bpupiY5i+WE3EXIZws1L7Y3b0+k5zyTWLQIqqTL53yKSPX/Cr4ENSJKwqk1XfLlVKg042Sdw/DS6kuXp6zmuudI2aYTwwAjfcRosb+hnZkqBjNTN/F2Ycld21CL3OE2WHrAj4a6P9k9QwByq1VGduWLX3CrLf2O62MoL9fabA/KSlGuUnz9KXNEm7UkwlMOezeN+ugpa4wa/N0aV1UqocpjNp3pbOUe8bE1U/FTxAOpdoNlRZgXiVDYJJpMWYiTyA7jaTZHQU9qZ8W9y1MJ+IikKupeAVo6L3221wNcKNNClAZM5ST3pjpG4IynrGWydHDQNRWO0cEMWESseOEssneYeQfgOZreZtysdpAle/PnPvo+00Xz1kpH2PU82ywxiRm4ZO3LiXuyGmRO6txkpjQ==
  template:
    metadata:
      creationTimestamp: null
      name: authentik-postgres-credentials
      namespace: authentik
