apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: n8n
resources:
  - namespace.yaml
  - config.yaml
  - sealed-secret.yaml
  - ingress.yaml
  - deployment.yaml
  - service.yaml