---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: n8n-secret
  namespace: n8n
spec:
  encryptedData:
    DB_POSTGRESDB_PASSWORD: AgB2w+uwSomE7hSmoG52Z5TsATvB02mgUQvo+gHM96kKLSL3FCLNM1RSc6KcG62mUmPCkn4N/8OK05G3nDVs2f56mctS9Z8uZoiOQZOhuF+gSBALy4V48Cvt7qR+d8Sf4SgsP3CzHIwHB7uHc0tPnxQiwVxq4d3TSaRV2TZSd1UIYZ5Ly8tKWnEoIZxou8BIJ8MqSK7MbJe88BapIS7aaJGpARQFF67ZY4VvqqZ2TTiSE/6/f8cMmLPay8U8i77Ho/BZEBWTDKKg0JXiYK5JeKNktTMV3pOEKj0/g2ftHRaNs+uV4lxm72E+dUP8yl924vsA/yajru+j02dxaoOrZbYd95BqobUOfOuOkL1m+AmLLzVHW+VFcSzrK2R1exaboOdqpmBpXRLi8GxsHUtf+LPli13IdNS3hq4z++V8THmGmKthuYOH9NONodQXbU/mL83MrR+MAnzkwiB7mscKjxLWr1VKjkrWrctpKFZfW6InmuE8nV6rvKCE10/aOsR25f+sfFub5fOoP8JVoflzAeENAioVxrp19PtqtqrOt1jyy5f057jaoldkw7fvO6k//V7IffS+17GAiclslstbOcfCte3jpkbgh/sdmLbQJNSb1J1VCbrwL+qqsM0aJeMNQajxkZLSpOh8M2mqUyV0DtB2pQZ3cj8g57190mJjppxLIFLg2HBO5utms/V9mUZNk1LT45vEHLJXVRYVAKCKk49wWTQ=
    N8N_ENCRYPTION_KEY: AgBsn77Bmo/kykFN6fJ8uxIDdBtlsh2qMdqTDX6ohnbuZn4r8qGfEReOv9skciRB7DpoMg8Q+M7T+MvzJMAyBkXV0YqZDGlonlDJyzImwuja7b59VgKQM5YotmZdv+c8n9xY4nc9FFEfuGktiz90YacLzsU+3/hw7Sth05pIQVOU3hAouZo0SGegOWL+z50eW67SPq5JuOz6gYphXdsiIx5iV85d53GsMTQ9j2mwP2My+Da9zmQ+FL+PzSMi+R6R8sDiHF1H0sORFaI7xhIBb2L+f7EG9k/TIn7VhXkNoxS2R8ulMysaArsU5K68pdz1H3jpi800BOY8jCuf5NNjVayoHS9iT4pnZRuYIOBgu0KjKxdjZsuA2fiwJQUtntzBqvFhGp89FUKvxHjEEa9+E6eGketGtMWjMZCBt6B2Aa1pIrjECwn5nCi1ytiDzflaHvINhn3PgwE5QvbIXgH/FuR7nVlg6Vq9TGR4ewq3/hWBw9nORWuquzfSHcVvvnl3Ee5PiwKG9gHNhHVLshXaWqrjOClThA4TWT4YPjvzDU6g2EJDahOVb8tYG/XuZqYx24ntQI1Hp05meEaqlHyTCvMZZr8DFBrzGF+Rn7lkhimRg0GWkrYbdrW/mnw+aUZlKNhb+y4rg2QR/bBLBisus5Dwalvp3Ilhypl9NmaPDrarDeUl2JflbnXq6zyl/5fazXpGJY29OHWuKog95dgGnMLeyAdBh22NzH2hf6Mtw43IgQ==
  template:
    metadata:
      creationTimestamp: null
      name: n8n-secret
      namespace: n8n
