---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: n8n-secret
  namespace: n8n
spec:
  encryptedData:
    DB_POSTGRESDB_PASSWORD: AgCvW+2BjTf7c3qVp56oTWxS+QhXS7XUXgK6t0Y7SdiEvIsmEGWSmY4YRyHmWJyrNnEHxqqNoALTeJ61rnNnLsUFx8bMAjqc5Pb0aPJbzbhPKnttAS/yheNCdsVb02j5E7VhBZGnx3cFaV8H4u+Fc4QuNKslybvR0zXznkC7lhEJ0xgIURGwk/GjmzyydtBa+xRVzyOYXhQ4GwONTudpGFKqx6zCyWJuhNom16+tTvKGlH5nU6GmHAfm43LQnCcU8Shs1mynThXvCgU2JRrZKxJ6z/8ssOer6wkXUgh4d6n31TgQzFEz1rW/0W8tKHjbq2iEXNd2yA9DQCOUThxXxanOZyUhNcPwE8k5ZKRo+3d/fz/HeDuRWZoC34t1OykbKB9iEJghiti2Cc4Hnz8oujbxT053DO3oCT6AjqiWo/704Qk7RPti6/Cu64WzG+c+obDpwSycYnGwjOw/XwfI2qFfHtKpdPEY7XYQmH+vFtlHC9Nh8vypgvyN/hDqGF9Gxxe/nnufoMG0ynsSkYV38MC64Ri+l3aiBU8eKsoT8/2Hc7xQM7Cuz0zPb0TXzgu+3KWYJlJJxKYpBIWUMrT+FD3gwg5qBDwzx9O6v1sj+PuxINsoPMOzOV+8BcVbdMJ5YmiZk7KOG8JIyMl6pvcLHrSbpCU5LDb9p8Ysl7WkvnnQpG1y8Owuodq7prQVWRElHG8k7Bsd7xRL0dIvbjopfAbjGpk=
  template:
    metadata:
      creationTimestamp: null
      name: n8n-secret
      namespace: n8n
