apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-nohu-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-nohu
  template:
    metadata:
      labels:
        app: minecraft-nohu
    spec:
      nodeSelector:
        kubernetes.io/hostname: w-ns3106816
      containers:
        - name: minecraft-nohu-container
          image: itzg/minecraft-server:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: minecraft-nohu-config
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "3Gi"
              cpu: "1000m"
          readinessProbe:
            exec:
              command:
                - mc-monitor 
                - status 
                - --host 
                - localhost 
                - --port
                - "25565"
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 18
