apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft-nohu-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-nohu
  template:
    metadata:
      labels:
        app: minecraft-nohu
    spec:
      nodeSelector:
        kubernetes.io/hostname: w-ns3106816
      containers:
        - name: minecraft-nohu-container
          image: itzg/minecraft-server:java21-graalvm
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: minecraft-nohu-config
          resources:
            requests:
              memory: "2Gi"
              cpu: "1000m"
            limits:
              memory: "4Gi"
              cpu: "2000m"
          volumeMounts:
            - mountPath: /data
              name: data
          readinessProbe:
            exec:
              command:
                - mc-monitor 
                - status 
                - --host 
                - localhost 
                - --port
                - "25565"
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 20
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi