apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: discord-provider
  namespace: flux-notification-discord
spec:
  type: discord
  secretRef:
    name: discord-webhook
