---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: discord-webhook
  namespace: flux-notification-discord
spec:
  encryptedData:
    address: AgANlXt6FlnvYU6xH0BUAhOXHc3MQbIFkX0EcnoJT0SFON0g3m8Qa9S/IupLMb7QZjrcLjlqGE2J4ked+qUP/MxhuTw6QCi9tDMbbkC7UyHAjxpf+9v7ThbkQmT6zdcJJjQeG+AxHw+CoA8/VHI5UKiLevwxYCACeB8kzcuzLskB1xeUFTh5F/QsLZPp+EU5m6LaklWDsicpqJwD1w+zlbLjK4e2G6M3BtT2+alXGksMyNTWB5YUedGAUJDu4jp0E0sTq34n4lIJAff5lW/GfGL1L0Bu95DdhrYYYLmf3d3ndkN/e0j+Hyvm8A3IrtRF+uOpWvl22B6GC6BoNeu+VzkNReQV33zoN/pCvK6tfggBhwnjnSHTLIsZWUf7QYrNX8MuAo0kbAr2usc3r7aOm9pt7SqCZz+6Vf/56d0D8UuEKYrWa1ZaOqfH71a9kuSVcMCsVH82byFrYxL4s9mJ7KKUyXX5vIkRxsM5tACDWxEjcAA7zw4tBKYzkKbAFmu3UfLSAk9okJmvN8qywv7V6lwVZAi0T5J6ccrL0yIOOhzNFL9EEhCPY83uuOkhyHkhd6LoJaR7I2EvdjcaBBYU6sL5eB8QZy6gkJ9R7fFOf4x7Kp3hemBsA9I32UvnzaFUtXRwX8TNfl9jBO5If0z2NlB2uWi2WtVLNDhYlftCOTod0S81PMvGUfP4aScnQ7zVP7QRRAKTKHkGc5nUrKAWCsVUoWRITpqVQd2Rvs8r5b82K8RKhHfqysKGPOJ9kJkYVtnydOnBCwoVlmPaGTlCUhfmAbUOF1AXr4VYgHlipzAkPTHJhEuyUpvwSYGtXHMeJJKzxizW5yx4zBrEMlfEfqWsFmCEwzNBXzDV
  template:
    metadata:
      creationTimestamp: null
      name: discord-webhook
      namespace: flux-notification-discord
