---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: discord-webhook
  namespace: flux-system
spec:
  encryptedData:
    address: AgBlzX55aYLHxbgSyvxM8rAkPeuUtZ3FXR7u7GCyM6MwHEdvoNud30IX3kc6+Ikq1TpMc7LCt0Y7hs9wAM7AC40ssZ7EOvK54cRt94hAy9B02FsX3XOrnmNDGVXsZpPyrQmWG0SJ40kM1R9Z54YDaUPNMYvPWNozzWvovN3lL+XQL9f70qHDcT3sXszetXR3IRKb+NHchaJbrA7WGWtmjKZAvWnsfpUMYozUpMABfoIvxh8d4LSETf+2HVy0lRjwZX9vPfQjwpMonTaVbUo75vR/rQvBZCMACQtHL+pw4jaH5acE/aCP9Au0VuuRmOY1IWRyFCfaoBY84cdgr3UMQonJePXL/p7VECyIaKOdeU9ZO/Nm3rcZ0fkFaDeN2WC+5bI6wVnhJWKA9rGZeDrUa7T4joCLgL35aTWs+pYOvN6xt72fZvnas9U3740nf1h8KyrKIYWFQMRYBjUVqICAChf+W59PyXsT+PcQS4hUdoM2XIBsrB42MQftOqRJunQE1UY+RhKPUTuJmpxTALLh05C24DesCxt/pDd3slgKJMcBlKOVlGsdF0im3a+Xy5iwrIXJjvpBuJK3xodvewsy/zE7wsQ/zGY8NyUN6FIRr5bKNCtEbsw4dlFeAsMJ/B+gvZiX44d5XN9ZZX4z7obVqEiHkFQld6ufQBNwAHBI9dFkKn8Akz3BUcl3tUNTrlDyLagrbL6V7OXoj+Kjmc8mlkKcuOmwfSKQxsv9m/LD9EAyfaa9/cYXxY+WdwjM+U0ooMjk3deOkNZr6l7fUPnjl5GwUtEte9VygJLSn/PhOumq3+SCWOl0FIprZ1GqCVn+uap27O8Ci072nTn1F5rNU4HMkwYVs4zHeTL/
  template:
    metadata:
      creationTimestamp: null
      name: discord-webhook
      namespace: flux-system
