---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-token
  namespace: flux-notification-discord
spec:
  encryptedData:
    address: AgBAqDKqb7Eqx/vKH8WXVy/v/2WRNcKXM7rj1ejeeIjzZRSyRhenzMScD9WmR35QdkdTBEIlUhVGAK4vhJ4oz6wuQBRlk3gLfkSn+Vp8G7sbhUwEq3LrZpPyuLNWyq0lirZEMkdJokOXDs+hciDNbLLKbcpWib2Ez+k3jaI8oaqDl8kj9E57l7fNsFnw6D0OAKwdHjl5HAKcbX9xg/cDEgpY8wTqQKg99xb888CUWWCYQFGSPUz9WgPF0otU1AYMXWr2NMZdUET/kBVEq6WAjDohy/WxnluV7KsfzBmlwazubf1I6cMZdqslt/Oq2LccoywId5kr81feWa6jrCHYBWpAx6SmQ8ItQFJDsgzP36tqujM4F9OKHZnNajRtQEwF8SwMNs8miNijj6F+J4euuSQSN2IZ3YG5lOqJCtHmhzlbGQ6+LK1yddRl7B1z2nxI7b5lBZSABvHaUfszRsZpNusHEHitPQAhUmNzR5mVFabmhCGJT4Af2IVcO622JHabWlQQjVmQ3zbPunYeojR9w/AgdS8/QaYABFpjuPo9dC7RkofmP/YQOO+5XVfZHKmhhZhVwT+APRQIXtWIupHZWjK9vjgeCNzeHlXhshJ0mQedYgNZXSG7o2e2WaZ0t48rDfyk0fvBrOxy/vzZTiLdg3rFdhWXyEIbkrK3BLRU39SFl+/l2Wk05q4iRefzHLZ0myPZk6yLDaIVvJBT1rjXID5qtyCCJEZnRENnKYv7Bh2D1P4sJvz+fbHej9cBxbZKe0b0s+etYmh12uGG6y5/qPYypLCRC2TEVbKVfkTjLKieVmRcWLgE0fefTbvmgGHe9g4VWGoff9nBYt91ztjfus+FC/7IPBp5LjxU
  template:
    metadata:
      creationTimestamp: null
      name: grafana-token
      namespace: flux-notification-discord
