apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: grafana-provider
  namespace: flux-notification-grafana
spec:
  type: grafana
  address: http://monitoring-release-grafana.monitoring.svc.cluster.local:3000/api/annotations
  secretRef:
    name: grafana-token

