apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: grafana-provider
  namespace: flux-notification-grafana
spec:
  type: grafana
  address: https://grafana.wittnerlab.com/api/annotations
  secretRef:
    name: grafana-token

