---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-token
  namespace: flux-notification-grafana
spec:
  encryptedData:
    token: AgCURufiSZxrC1hSs7WKVFKcsaFLptq9/jw1mWlji8ujXXXQWFamL2p/pkx7Pm+dMRTLIextnqea7y5ObFV/2kdQ6f/uDQJzfGzzAW1RaQqD2k+m4W4v6+lbM4z7FGDjfK8ge7bI10/3D3BljkcXCkySUFQ+Y2ozSzgQrp4ZzmiJrG8uUWbhnLW7jFxyBYSfjs4Q8M8PHYOtBD8kN6mnMUvcHHKv3XWau3nYauROnoAMrJf6AGDtnnLTZGT5f9UQnE9UZMLR3CpkJ29RwalXKVn8ddwPMOS+h8+zGHsQWHKRqEWmNTB8UeMSKCTk87fFHB7W2Dx/W56iXbRew/16e+odfpSSnYKoy3KFUTIWarqnY+FghkhnEN5QxCsQarTFc1PdvuTfRi1VjPh5nv4VU5jisqNp6Lr4LLxYhOk8bXjKMpi7YawThowlXVnkayGi6+B4C5Y0SGskixvYbGu6ciGuV9K+qzmftyEyDV2uR8DF1J7rs7GnzDn3lTuPwjFKp1bdnoR6Y45k2sviinx5r7E0ImLGFF+4fv3SPYc4cMD05UBh938Ekzk7txq/e3WJ71NaHWKe1VlQVSrZV/L6cEQ+SSVIBEZ1ZbF5riRF6hcm5eKcH2qx0v6vnQb3f7WESegShqbXU+ZXYmx3t5eRZlCI1WkQYKtQzqJLb9DmKWSKBMgj2hfYfPgA4OUo3EApz0wtEA2P4grMG2pdyG5ykVmhTGtngDUM5pbYjzZj5lZxiqCd5JPIWqYLU6iyy7mY
  template:
    metadata:
      creationTimestamp: null
      name: grafana-token
      namespace: flux-notification-grafana
