---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-token
  namespace: flux-notification-grafana
spec:
  encryptedData:
    password: AgCJoGsP/G/OXvO2DOxoonZ+UNeQITEev7OBAigEmmVBCh73VRj9AAJvS0smZX7WR7KEzxdMrF/+hsRFQYdDJFP4Riv2Ckw+5BqVO9+hkjR8V4ojYmon1LGCf0LZLcpKgsfldst4sufP9IPTmT4LhhcbZnf2F/UXxtoJd1ibGHcqRbh7wrJGe/Eu5eobvEPGU1h39vl8rfMGn/03ojklrxNr13N0c8ImGVWIaqo9CcKV9o9FVT33nMqPbjbn/uLoqzE1ZVzU7j6kKNOU0O/FlDSs/SZ30MTexuGRXy1cfsE462mQlbT6wvdJ78Buw4XWdg8+YhqYSox86W8g72rZAZOcKxGjA4+6/lXCHF5eB27N4uF0GvzL6h/3uF/SkGj37axcnUnyh9v9hgM0NwwVq4FEVqEUeuT4FzfSH+rj+/mGJ2lx1GwNTswCzHlIodxkEKPdp2lesVpfgXaaZNCRzB8PDgZ5eusU1Y5+sKCpfslDgvMBATmkNg0+2w+buuMCjaWrRLuOndWd2qOkeP3v6f3JEvOlzkV1YXzMuBaolRctufLup8EbACAcYHwDpsRhaGnb9Fz3NwonSYnlJY+d/92la28U+5OKzTKwjJkDJR2f68lKbX0+oGdYFee4/p2j+dIKThZbTSvIBR73JXVoyiwS9Nk9VgcXQRmJAn0ZLHd4lR/mKWIwOB7dJ/E7tlFN1n2XxWUtmr8bEWnej7joWFP2wns=
    username: AgAhIgl0AtAepyb17V62RJa+KcbFUiVI40SeL0yQZDwZRxv2aX79fYrzCajZrxKg2chZHtlFYTELuhRmXY62CNsq1IIhigq5dtaYtQOeX/4+9L7DnQubVKvGkPKIcuUhewhTaRvFuXrsoq1YuSlf0AF5ILX8BRz2EUiX0GtJFxSoGqCMG535vUBbrw96KmLVXXZpQOcLO6lqKcdlEvolDDdig0OxqqCLIc3/M0mlcrSObt66rpmZ52m7+aI5ZF7KDNsuASQwMQiid99Aef13zlnMIpjQ8Z25es4x4kijmCLSpHqOTJ3Po4C5RZztj4+e7qGDd1TRspGTd+g99qQewE26guf3M/9DBsRHVF+P+euNCPOz/eVf5YiEFuH7eUR8XM1FcrA57G5gZ+hXh4fpPwa0dzbWamnkskmU9KVqkEVYtO1kO12j7v3QlzO8PLf/pb/hIS+berBboU4r47gA0EPcYR+dZuxQdm1pzjoSWBd3RftmjdrkXMUD+irleQsmdGe5+iChTXMpDUOpo3AfGr+Ot6I2T//lo2gUQMELDsQhyEds3fpJEryZ86mPj0Cd85x6U0bAFuXipk68LfmCln3VhyG3rC5gHxY9I6ir2mQbIDkV0aB0vG6gMK5qBXfgMdKtmCny1Hu/gx2+ruf0NVdougZ1AM/8nCBTjTGNgHCVZocIpfEM0gSfZvvMP8v7sJ+OScYszjUyXjc=
  template:
    metadata:
      creationTimestamp: null
      name: grafana-token
      namespace: flux-notification-grafana
