apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: quickwit
  namespace: logging
spec:
  interval: 1m0s
  chart:
    spec:
      chart: quickwit
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: quickwit-repository
        namespace: logging
      version: 0.7.15
  values:
    environment:
      QW_METASTORE_URI: s3://[BUCKET]/quickwit-indexes
      NO_COLOR: 1
      QW_ENABLE_OPENTELEMETRY_OTLP_EXPORTER: "true"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://localhost:7281"      
    environmentFrom:
      - secretRef:
          name: quickwit-s3-credentials
    searcher:
      replicaCount: 1
      resources:
        requests:
          cpu: 10m
          memory: 512Mi
        limits:
          memory: 512Mi
    indexer:
      replicaCount: 1
      resources:
        requests:
          cpu: 40m
          memory: 512Mi
        limits:
          memory: 512Mi
    metastore:
      replicaCount: 1
    config:
      default_index_root_uri: s3://[BUCKET]/quickwit-indexes
      storage:
        s3:
          region: sbg
          endpoint: https://s3.sbg.io.cloud.ovh.net
      indexer:
        enable_otlp_endpoint: true
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: otel-collector
  namespace: logging
spec:
  interval: 1m0s
  chart:
    spec:
      chart: opentelemetry-collector
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: open-telemetry-repository
        namespace: logging
      version: 0.117.2
  values:
    mode: daemonset
    resources:
      requests:
        cpu: 40m
        memory: 384Mi
      limits:
        memory: 384Mi
    service:
      enabled: true
    image:
      repository: "otel/opentelemetry-collector-k8s"
    presets:
      logsCollection:
        enabled: true
      kubernetesAttributes:
        enabled: true
    config:
      exporters:
        otlp:
          endpoint: quickwit-indexer:7281
          tls:
            insecure: true
      service:
        pipelines:
          logs:
            exporters:
              - otlp