apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: draw-io-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: drawio.bytedragon.tech
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: draw-io-service
                port:
                  number: 8080