apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: monitoring-release
  namespace: monitoring
spec:
  interval: 1m
  chart:
    spec:
      chart: kube-prometheus-stack # Nom du chart
      version: 69.7.2
      sourceRef:
        kind: HelmRepository
        name: monitoring-repository
        namespace: monitoring
  values:
    grafana:
      ingress:
        enabled: true
        ingressClassName: nginx
        hosts: 
          - grafana.bytedragon.tech
      admin:
        existingSecret: monitoring-secret
        userKey: admin_login
        passwordKey: admin_password
      plugins:
        - https://github.com/quickwit-oss/quickwit-datasource/releases/download/v0.4.6/quickwit-quickwit-datasource-0.4.6.zip;quickwit-quickwit-datasource
      datasources:
        datasources.yaml:
          apiVersion: 1
          datasources:
            - name: Cluster Logs
              type: quickwit-quickwit-datasource
              url: http://quickwit-searcher.logging.svc.cluster.local:7280/api/v1
              jsonData:
                index: otel-logs-v0_7
                logMessageField: body.message
