---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: monitoring-secret
  namespace: monitoring
spec:
  encryptedData:
    admin_login: AgBhKjbys6YJBtmK1qUR2Yjsy25+HMPy64xvEZeQtq9OxypjGP4b3WwEVVFC1jZfA/+BU/wj+a4AlZ8W1fi9weetKHIlxB1GeF+npi6tQbOnQ36dVG5h9Z7FUi4s6gtb4m0CLLvQQfq9+LQpmVa7FmZDG5TC9ID8sAz9X/QRHOwl44S2OBrMRnWqgil5I29MHG/sP0ywssA9fKwv432UsUZRu3F1RA9DXdxVuKR8a12VDhG+5/Jw8EOL03OPDbtBS8lU4l4KzBdH40S+Fec1v/ff/rb4MpLVjr+T+g7YS6VepV8YYe8gLvMS4XVrYEN63fQxqcajCVD7NryJr6TPvVLF5a8uK0+GiTPDNyI4RwUFgbG3hi9q3xrS63KD8QYGQzRLFA2vZ4O2aMGLaMQ7f3+QgmbYTidjIHBeLbYAcF5qTCrj9FwuBRApgzmL+09d2OwKd2K8+Wtz67CZR+quS/nRZ6s1QTyHZxHn5lNeU1VYch4HqsYnfYj6YWz8Ra17Rsw6NScO5G2XotuvmDA+bW4sLV9NIYBYAaYaJtlZbvBgSFDFCdIwolOgo+qPtCM7lXmWzrTzRBEaYdRqkP309pMn2Tb4H85SUUTvN3GSrc29PZfv3GX2B2xI/g94mGReNf4VLj/b/IOxTE062j2ST9i6ceRqiTkr+sJQRJC1cEHWscT3Hvtwgsz/n9A4QHmjOWWBbN2T7cFEIX8=
    admin_password: AgAZ2yy5iut1D65r7NOQsxGfTknNaQRSZ762RjIflAho0ZUGT5aSl73jQn31HXfw8roymMz/dVgZLSqVvQY0tRM3npa+min116YDtw6z/zfDRrTwXPZOoU1LRX0DFmlsE+jJC2aj8qa3lD+JXb0/izZ7xwPFZLIkO+Zp3InnDp+Tv8VUjuH4ccWHasJ8tffcjBfYXg4VRIT9JFYJDcXmBe2i45zdAVy+6ua0/JbNKhznFfO6LyC323MIcSrElI80k7bLZsxicB1O1MmDK9/Wok5UOUy7vHncAXTUGwnoslnYwybxC2TKNyxlhspSXI3gRhmTEdf6o1Gb9WFQGyOJTRcapmmjDmb8oHwALIwNFMztyez0vg415jd5oIA5et4OJqtWlCmn0OdLa73Z3SQtTmEyP16nk0DtjVv5cTik3kDwvFaivTC5zP/aob2Mc28YlI46Si0RxiY5QGofwV8L4NU4JnGKx6iV/ukR6FLOQFy643pHVNXNBhiMpaBmKPCzMl+Gw1W3Bh6ZROQIXsP0UXYKKRIKTtPpMt0hCVpA5LsJYKBbBcZ9SQid7HveaPpHy9TAtjGbUQaHTbfwoKfTDN92b4yl6jBP2O7DhbS0POJo+kkiv8bV6kHkQTamcHwn9pbo18BwIkMhxlTOhB1uUyKC7IvQMmQHznxzlF3AcjneONkvvauXo/hBVCzlIyx1SgtjCofiOZaRKlWB1l1hLhJ+u2g=
  template:
    metadata:
      creationTimestamp: null
      name: monitoring-secret
      namespace: monitoring
