apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gha-runner-scale-set-controller-release-bankwiz
  namespace: arc-systems
spec:
  interval: 1m
  chart:
    spec:
      chart: minio # Nom du chart
      version: 15.0.7
      sourceRef:
        kind: HelmRepository
        name: gha-runner-scale-set-controller-repository
        namespace: arc-systems
  values:
    githubConfigUrl: https://github.com/jbwittner/bankwiz_server
    githubConfigSecret: github-bankwiz-secret