---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-bankwiz-secret
  namespace: arc-runners
spec:
  encryptedData:
    github_token: AgAJthWWEwIq+U6uHFdN2InY7SWTHe7tw5zhzdOd8DeFoc7efrrEVktpMeQjGBYLTHa4k0zbnBHXtD67gqF6jp7cwteu4S/Lid3L0x0E1vRierAKPezWVNqiHmO+mj2jDLGjLG1fpzoWykUVgS50Z66jQMdZNrSTgUZTDtk9xFMAzq3Wyw6ONXEAZkcRudNkvKZTLNvpzszwiwKlQX0grsrFRZPzmInD9PE+Qr+E1MObzbYXEKQb9QNYUorPPwYHrjVPjh4XgKYCa1rkW1CRz8d2Eb/B9qRArC47rUT1m2ID9MRmURZ1CySjvLvMOkso8blXRYIYlfsFsvDR+3Ik7Jw3Q9JvgXlcMrkZ/9yq6d1fMZqC54hvXYQEytxqClqmONcAhwQsOjdTjr4uP2NvbAw32BI/kSGRlbVQCVaBtuqrj18bfNftUl6pBpg6chbwtJIwcSeeG6TROG9dzjfmBYIHZ1M7oHe04WdxMusckgX5+jU+Gr+s6bPZQt69R5C32A+V+HJVl60B68CWof4b/6TxTX4p2F6Cg1nYBJMGHKHhVahooRPVt4xk6+H0iYoh0TFoQ7hloVXU0YMB10iho2QLB2IZtPmrOsxJRUUkH5F6JkNk24t+PBs2q5TGPMgsggQoH7a2lC56fYjT8JgTMh1kRlWJ/yuhgyM5Mdp/G65Dg4N8AryXBeWFuTkaD+xM6i23cdlzqiZ6WBYOCLWqnwovvsXdYkaLyvsj/2A+Q27FJX8TYABG+My3XKIY5nbwnZRmXVvRA04wA5gBlroVZwdGj3DJp0DSCMGwy34qjQFR9iux3Bet7RcuJ2+Y10Q=
  template:
    metadata:
      creationTimestamp: null
      name: github-bankwiz-secret
      namespace: arc-runners
