---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-tunnel-credentials
  namespace: cloudflare-tunnel
spec:
  encryptedData:
    credentials.json: AgBaTsGVHK4M0mBGsejT8BKcRo/GHsYsod81HE2auFC7BIthCEy0plYwV9jsP3q1QxG7HBb/jRc886upz9ESGqMqnmOKXbG+j5SGrf/GoimFltwSNo7QjAAbDTAUql/vm+bZ8uMtDCy5OrY3qokeXbzQoy7dyAoy6FD7x/UWRyrta5hdL0Nwx5SjNgW8SaGlXRMKwr2uQpWhRfQ+EGrAOdxp8adonb/+uTbomL2JKoPrrF+XXkdVHKBZEdc8nRj3fHTvFn2KpXFO99n6Qo/HQ3hXTjQWX1vIkow288ayhwPzkBF3ONecyZDwKRfz+ZXieiA8P8qUWbvAGbUvUBfsFlNX7LH3G24kQpsy9uZL1/nCEHeBCImJFDxWif/iTd9KQg2315JEY6OpYveIJMzAVGjcZHjFsGATpsI+HbovvSDrWQ1/OpN+p99hc55hQe31zGwRk2kg8xuhgZiHLh5k6dxsio8CXSUqk9EAtQkmO/IuIHq25BafhigwR3FzhXKI9Acy5D8+6T9chMRwLG48KLLRfPeYmlv7BIS30ZMCStq1ipWuz08YV7HV+rWZtAGn2XWPXPSaiGe87wksCr4aORSxFSLfRb9/UnsmFGlpeHFBONm5E6afcnqoNVwIG9+fQ1+9B1ohs7S17KR3unW9euk1cJ9wHsatl6guNvts5DsBEAaG4ni/Hqx3JCqwCV+kXdyMHydEMq3zLA00QkUbYQrZRdKyhkqecPVBrXg/tHNU5oQKkXAK3+fmsO3WIS398haxHQP+Oe8GoBYcFMlBdwBSUQxDY8rpeh1IR8vgR+NxOLKw3bsJVBCBcd162YZw3CIHmMzwzPEGBVnPjAj/11jEO7rjjArenyAAi3kt1KGeGkCErFJszIRPIxpLe3UbCyrTtxsw9iUpWZBsN9f538E1lvU16P058763uGQCQSSf
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-tunnel-credentials
      namespace: cloudflare-tunnel
