---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-key
  namespace: cloudflare-tunnel
spec:
  encryptedData:
    apiKey: AgBhFUW7OBl/Py7fecjNaCs8J1bnnXF5M9l9tamiiVYraDMtqJhxJCLzYAB3UWfovWXSNrWysf/rviE2GH/hZ4S5G+XlIB2irAYHCD6x46LZfw3/WB0JBdFBzEK7Y0JOXdi/bNbB0ftRejKWDCc1FQjXszy6KQ+XGyZJjhs18bAPB4q5+eIXd/gJbq1GqrLoVn4lCQ+z6MgsNfaqbJ9WsXva8UhIRz93FSkrA/aUdU3NUOhVEoijTya6/mawENDSR863hcBe7V2n9LB2XBwpBz9ip93ZuQCGJzE85B25sHFjXPt4q7qWP26VeUKofnhJTF44jwl39XB0WFf/ptQBMKt7RFn3xDaUAUewQBoyMEd9eqCUDYa/6dp7xpcyIl7lWqBBCwkDTuR2EFF9sJqlO88g7/4uTlzYpnBAk/VRnVxMFapmuj6FzOvCTN7cv39l2HT7V+vPN+LeC7bcYmRqte/LsrdqBPF9uy+qXoLaRzJqBCUF4/hTObreW906KFkTEVNfThwVoMr4UcB1fTcNlA2ypIpiIuPjRIBWHJ4h8NX/rtQLfvk3JGvTRYZ6ZBi5p10lK5aS3GnKmJpQ3JqLHn1aWP+f9rj67TWQWvL7Zyd13KBXkfcdZCpt3AwUXH6myivxrDLFNdJcIO+8jfj9fBNCscj0BNlOxlr6ILMvZkELs3YiFnaSsSUWkXHxbJwWAag2TUocPmMDvhxlCJZmIgUlRt1SfEWDLPBFdcz9V3HUKFDbh9R0J61H
    email: AgCVXz01L1Y02hbRTl/XJ0BB+mtmgzbQHR7TiHtj16MMpEJAdMuApZPr4VXZdOcSmp/A/nshDlQiLUjrWePrMdKcZLnKOOklBO3ZX4inNGNTygDS9kThdqX8jRDJOYEqi4pY8IS17g2tR9dXLyOvmI4N8Ce1kBM6A4NjTuKII2OnXTkdXF6+HVS7MBgeAJcbsBXl0ZPnRdKOrzJ99BjfNwRDz/sa+tzgWCbHiiY1VkTgQl6NPeZwpG3+M42wbWDkkrsy4CJSwPkNUXq3jWASiLCIbzSifVE5wHthR0s2eEQ9222R9X7KgbUIGqAR8CRxJVf+XEVelXNUjmeD8cNuJ3QTAZPWWHcB4KlR0R1x85WzhZyRfz/kxnsCjFh0e9GlhqOv4pjwMDIfwMLTuM4Mb4XLZWMiJaIsEMwIKienEcS/QvTfcbWwFpkrndYKemi784RdjzRwpv8xo4mrCELIyAgpNjLmYaKzpzhalQkdR/d0mrhqRR+h/CMrK0CGMS+6nUrI0qbYx9YB0Gn0ntj5baiGPgvsAtZIF/N8w1Hp490r1FZHqiuSP3gFLEenUOVDjMVd9t3Lh8ltkXqE74WAPKd5y228ZXcdYTnuxL0dAVnl1MrD2LgirMJr2GVeOVaJIZ/a3H4lbFpd1KVsfDLTAP1OtVEqLMwcvu+91KgtzN/Yp8m4tQmnkNivXhmMf0BRkHIrhM4MiIdIaqFLte3wVgWvvX5Z+QoEUf27JM1Vs5xeEQ==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-key
      namespace: cloudflare-tunnel
