apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-metrics-server
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - chart: metrics-server
      repoURL: https://kubernetes-sigs.github.io/metrics-server
      targetRevision: 3.13.0
      helm:
        values: |
          args:
            - --kubelet-insecure-tls # Allow metrics-server to scrape metrics from kubelets with self-signed certificates
  destination:
    server: https://kubernetes.default.svc
    namespace: metrics-server
