apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: excalidraw-release
  namespace: excalidraw
spec:
  interval: 1m
  chart:
    spec:
      chart: excalidraw # Nom du chart
      version: 0.1.1
      sourceRef:
        kind: HelmRepository
        name: excalidraw-repository
        namespace: excalidraw
  values:
    ingress:
      enabled: true
      annotations:
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
        external-dns.alpha.kubernetes.io/hostname: excalidraw.wittnerlab.com
        external-dns.alpha.kubernetes.io/target: a43b34e6-c752-44d1-99a5-cefa29a1fe53.cfargotunnel.com
      hosts:
        - host: excalidraw.bytedragon.tech
          paths:
            - path: /
              pathType: Prefix
    resources:
      requests:
        cpu: 1m
        memory: 10Mi