apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: excalidraw-release
  namespace: excalidraw
spec:
  interval: 1m
  chart:
    spec:
      chart: excalidraw # Nom du chart
      version: 0.1.1
      sourceRef:
        kind: HelmRepository
        name: excalidraw-repository
        namespace: excalidraw
  values:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      hosts:
        - host: excalidraw.bytedragon.tech
          paths:
            - path: /
              pathType: Prefix