apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: monitoring-release
  namespace: monitoring
spec:
  interval: 1m
  chart:
    spec:
      chart: kube-prometheus-stack # Nom du chart
      version: 69.7.2
      sourceRef:
        kind: HelmRepository
        name: monitoring-repository
        namespace: monitoring
  values:
    grafana:
      #persistence:
      #  enabled: true
      #  type: sts
      #  accessModes:
      #    - ReadWriteOnce
      #  size: 10Gi
      #  finalizers:
      #    - kubernetes.io/pvc-protection
      defaultDashboardsInterval: 10m
      ingress:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
          external-dns.alpha.kubernetes.io/hostname: grafana.wittnerlab.com
          external-dns.alpha.kubernetes.io/target: a43b34e6-c752-44d1-99a5-cefa29a1fe53.cfargotunnel.com
        hosts: 
          - grafana.wittnerlab.com
      admin:
        existingSecret: monitoring-secret
        userKey: admin_login
        passwordKey: admin_password
    prometheus:
      prometheusSpec:
        retention: 5d    
        storageSpec: 
          volumeClaimTemplate:
            spec:
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 10Gi