apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: monitoring-release
  namespace: monitoring
spec:
  interval: 1m
  chart:
    spec:
      chart: kube-prometheus-stack # Nom du chart
      version: 69.7.2
      sourceRef:
        kind: HelmRepository
        name: monitoring-repository
        namespace: monitoring
  values:
    grafana:
      metadata:
        annotations:
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
          external-dns.alpha.kubernetes.io/hostname: grafana.bytedragon.tech
          external-dns.alpha.kubernetes.io/target: e2ce076e-6567-4837-ba6b-fc9a6de53032.com
      ingress:
        enabled: true
        hosts: 
          - grafana.bytedragon.tech
      admin:
        existingSecret: monitoring-secret
        userKey: admin_login
        passwordKey: admin_password