---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: monitoring-secret
  namespace: monitoring
spec:
  encryptedData:
    admin_login: AgCCsAGY6RTLWZ/ReJRaI8xy+WdKwD7We1CAXc5/HJX0cSFT7QZhionNUvEv2cLxKKGhudzZg4y8ddZdHagT6Ox+AqizYvJSl+c1hnI6isyJX1Ugc7vxBoPDa3pqKWsZJXNbe9Vex4cVSC7bpj5xZZ1MyLYEXHrnzupGk8yPO6tZGIw2rmwcZcgOp/JMCT85rXXsYflDMfwjlAPPxUyPBIidXOAtjK87turOS3o2Qk09lofZICsLLsVwOJq9KL3DvnlkTr/bDdURZ+CEs+LMGi5u3Vi21gI3r412nlgp+kbITb/twlDqYeeMY30b/uzpMBZJH0r8h4UYkAV9zxjXN2FK3HHcf7q5Ee2ZPI5iDjceqfwQ5sYhDUKmIw9AEqTBPGZdttgeMliEyxys8J8QJnCDQtv+QRsoPdAUHVyjPHkLZB46KULD5PBPfqU8jWHwVGft6UIr57mCHf4WFMhvLQkAvHiyH0R+J4Z9JBW/zFhuaei17nJv8CrvJTx9V9R7qMaVe3LirjiU9ktmOecgHthqwQYvIreMc/AVOGXCMFMbRlEhcZqf7ps58nem0tm3diIQJlid0Pu9z9GY1xR1LeisIT/umq5kCUdk6+Pf7iINyAErx8sPy+dA0ZrepXbaj6f9DQ0LiXtg/YJIr1HNy/clJG6IvvfUlGEVscAdaWR3qBWoMoIGljj7uYKa1nWp57z4JUZJj8Ami78=
    admin_password: AgBk8uhvDFw9UNBrPL2EDvVv29k1PzAI3CjkInBXLYFRJ3J7ZHRSRiIJf1UYR/Ofml/oqpRupZZNW6B5omsQvoALPFVGAQYf31tRtrGhGalw1PVIbPcV9qUPdbXH2N3neAYFhXDD286NbALNeuYB5QP+2qfy7h/oVBUlY3TQpMRsxUssnSWiwFcYV4a6CDHEYsQw9fLgMJp3u9RDSgbS8cVDYYdvnJIWbcqoT7bAXeFCoiR8eMtRod7WT+gwL1ntQdxCOVEXo9LH4cDqVe7RZejV9n9Xa7ms41EN4M/s8ZI0c7OoO742d4ICnVBbBg8hPRdtfRc497XlJXoMb3/0VJ2S5/GnnSFhIw4+zJsYQsL1EYSvNE+t0AxkDOwRQh+vPgBxQnonZsEV+S+nHw6n+Va4CtVgfwUMnpCdWVpPST+GX+cMw0d8uIOjp5UDjxD0puiGIKl8HmAeAxP+28Gy++Q5j35RgBSApPcSwhQqKyFGJp1RwzXRTaav2kQ55UcQgxyXtsGFgTSlN0SVM/6IZKx6VMmFsi9I+s/l5UpHqzIEIbkCM3LrCsQkWrOUDdMNcVxqiJE9QrfpqAKvcSdQyiAQ4+rt4Y1ggZlPh73U6JQ0gLN9MqS+ay7d1Obn+1imtyjCnqRuX6uF26DIVfDahVcOC4oYQ/PJWwoZWArsURZwP1pw7+GSAd9PluscA8YRRRoW+Aq6mDrRML3it1Tl/7abccI=
  template:
    metadata:
      creationTimestamp: null
      name: monitoring-secret
      namespace: monitoring
