apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: privatebin-release
  namespace: privatebin
spec:
  interval: 1m # Interval de synchronisation avec le repository
  chart:
    spec:
      chart: privatebin # Nom du chart
      version: 1.7.0  # Version du chart
      sourceRef:
        kind: HelmRepository
        name: privatebin-repository
        namespace: privatebin
  values:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
      hosts:
        - host: privatebin.bytedragon.tech
          paths:
            - path: "/"
              pathType: Prefix
    resources:
      limits:
        memory: 512Mi  # Augmenté pour éviter les OOM
      requests:
        cpu: 10m
        memory: 512Mi  # Augmenté pour éviter les OOM