apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: privatebin-release
  namespace: privatebin
spec:
  interval: 15m0s # Interval de synchronisation avec le repository
  chart:
    spec:
      chart: privatebin # Nom du chart
      version: 0.22.1  # Version du chart
      sourceRef:
        kind: HelmRepository
        name: privatebin-repository
        namespace: privatebin
  values:
    resources:
      requests:
        cpu: 1m
        memory: 50Mi
    ingress:
      enabled: true
      annotations:
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
        external-dns.alpha.kubernetes.io/hostname: privatebin.wittnerlab.com
        external-dns.alpha.kubernetes.io/target: a43b34e6-c752-44d1-99a5-cefa29a1fe53.cfargotunnel.com
      hosts:
        - host: privatebin.wittnerlab.com
          paths:
            - path: "/"
              pathType: Prefix