---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-metrics-server
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./gitops/application/metrics-server
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-monitoring
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-ingress-nginx
    - name: infra-sealed-secrets
  interval: 1m0s
  path: ./gitops/apps/monitoring
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system