apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-metrics-server
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./gitops/application/metrics-server
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system