apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-monitoring
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-ingress-nginx
  interval: 1m0s
  path: ./gitops/apps/monitoring
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---