---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-ceph-rook
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./gitops/infrastructure/ceph-rook
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-sealed-secrets
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./gitops/infrastructure/sealed-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system