---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-ceph-rook
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./gitops/infrastructure/ceph-rook
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-sealed-secrets
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./gitops/infrastructure/sealed-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-ingress-nginx
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./gitops/infrastructure/ingress-nginx
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-cloudflare-tunnel-wittnerlab-com
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-ingress-nginx
  interval: 1m0s
  path: ./gitops/infrastructure/cloudflare-tunnel/wittnerlab-com
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-notification
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./gitops/infrastructure/notification
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
