apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-longhorn
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./gitops/infrastructure/longhorn
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-metallb
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./gitops/infrastructure/metallb
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-ingress-nginx
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-metallb
  interval: 1m0s
  path: ./gitops/infrastructure/ingress-nginx
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---