apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: database-dev-release
  namespace: database-dev
spec:
  interval: 1m
  chart:
    spec:
      chart: postgresql # Nom du chart
      version: 16.4.16
      sourceRef:
        kind: HelmRepository
        name: database-dev-repository
        namespace: database-dev
  values:
    global:
      postgresql:
        auth:
          postgresPassword: my-password