cloudflare:
  tunnelName: kubernetes-wittnerlab-com
  tunnelId: a43b34e6-c752-44d1-99a5-cefa29a1fe53
  secretName: cloudflare-tunnel-credentials
  ingress:
    - hostname: "*.wittnerlab.com"
      service: "https://ingress-nginx-release-controller.ingress-nginx.svc.cluster.local:443"
      originRequest:
        noTLSVerify: true
resources:
  limits:
    cpu: "100m"
    memory: "128Mi"
  requests:
    cpu: "100m"
    memory: "128Mi"
replicaCount: 2