apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-cloudflare-tunnel-wittnerlab-com
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - chart: cloudflare-tunnel
      repoURL: https://cloudflare.github.io/helm-charts
      targetRevision: 0.3.2
      helm:
        valueFiles:
          - cloudflare-tunnel/cloudflare-tunnel-wittnerlab-com.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflare-wittnerlab-com
