apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-cloudflare-extra-dns-wittnerlab-com
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - chart: external-dns
      repoURL: https://kubernetes-sigs.github.io/external-dns
      targetRevision: 1.16.1
      helm:
        values: |
          env:
          - name: CF_API_TOKEN
            valueFrom:
              secretKeyRef:
                key: apiKey
                name: cloudflare-api-key
          policy: sync
          provider:
            name: cloudflare
          sources:
          - ingress
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflare-wittnerlab-com
