apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-openebs
  namespace: argocd
spec:
  destination:
    namespace: openebs
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: openebs
    repoURL: https://openebs.github.io/openebs
    targetRevision: 4.3.2
  syncPolicy:
    syncOptions:
      - CreateNamespace=true