---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-tunnel-credentials
  namespace: cloudflare-tunnel
spec:
  encryptedData:
    credentials.json: AgA2gnfnLsblKl7mESH0N92mk2ds2kScy8E72O8tcgEDikccsVADtdnH+LnYxOet4avJLKNH+l4wvHdoDVteN02xqfbnyJbS/ZW21AlSyk3a7GjGE3iG5p7ccbRLxjH8pQK66SUPQOYFAxLswDIP7ujgUsshJzm09WGHWeLk0IQ2+/TJVdF//zl8YfXaXT5LEKBMUjn3MBeJPjLDL3l1NMHiMTZAGmgOk6hHNi0N9L6EaxOTyu2sd2eP7An7wNyrIELEAZOC7ynxAQkVUBu8CuJPgA3Bo8PiaXxVydSr6HN8eESvq24GgvVvNrmwWsYr/k8oFTHEJZS8L7FWHnioUM/vkn1bA5or4y0/Ost/+WQwzxkW0LqbwaXmLIymGhtR/Y56myncQ2u4qUXX/Njpj5RDhVuBkTHxl3ecRog0gpVTC+2asWaFUp38pG3CsC1gEH48kbeoJOK+W6CIPTZIsIGiTd7Ff78tSnhnVgsecj5BoLD2wgVcpwlLCZZJgRygTQT9gWfmSJdRW7Zoz1lRLUkI1XW7iXzBpSZ3AAjs+AGezVvinu5l5XVzYUD7JwqYksIDStUOB5O6kDbNZwFM1Ggf58FOTffPW87XlLmd/h2xwTtti4XDgVaRTMHD5dn3k86Lsj3po8HCF2jBuMONxSQNFS2+joudT5mS1xAMQ4b78Kps31gUKPjGtMY02EE/uikhtJS84d0UloTYqaTV/lVLUDpvIUD1+UGLNp9whB1fvxjRP/TniFYdbtJq3U4cest2tjxUSETw5XDFKUWM2NjiX7lewJll2MZzpxIdnA067oELN2LJCPgFVVPfZBixZMELDA31N8jOHFgP9Yl8xlpgShiunp9yN5FIhtOun6NdhBHF6fsahuBL0dFd1gtaN3cuxHW09P8FLkD0AiVPTXDsuTFXDsEvcVSO+P4PhqEM
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-tunnel-credentials
      namespace: cloudflare-tunnel
