---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-tunnel-credentials
  namespace: cloudflare-tunnel
spec:
  encryptedData:
    credentials.json: AgCgGdC+vbcIE26e9IAP34iptLMgjEbnKp1dlumiYlNPh8Z7s4GzOr3XM+i5y5MQZJGVU5QqYXBg+CbS4WhygDq0XfxOBkoN2jVdM8J9NtACfwW9Zd0hwGDiDcesBmZxJlAFCaHT+4R8GKTRZAy50aeQeOaNH0bbH3zdQY/O4dRItUU+loqK42kU7Mkn7OoIrYt57Wj8BFABxhLV46RcgBqWlcKp9xlJ6SqxSEtsyo+lpVB1qJqAaPwhHwhxOLUdFyR9cgKq+qCQmQGr8xYJSwwlg9oTgOTqtk5JadDHY8FCz2dk36AHS0rB/u0zcwApxdRYV17LKjd64dbdEpMlVOkDo6lBKtkyaISbzBspS+tnWECSeb8zIHT+6e8Ed04XbaKEJq5lnm8pVvSvZsxon+soiJfTFvV66mM6RlUWN1idLgcsTge6bHuXTYuVZWsms7nOtR1gzGWz3nafJs/KHfWns7fabUUUka0BAMzH3RL7OaQmvnj8ZBMayIxTw75ut0X45a5gTH1JkstD9Hsvl9OXH4LfTSX7frROLPhneAaV9dqvs6BejYoG35Xt1uaW8bSTbyZ2KHMGQtJDjmn0jIIzVRlFlvVC7+SlPMfHKpW7Hmo9N4+aZFrSIJ17pCW8aFrv9ehMPOARmuI90zjiojQSsBzGeBVpiJKR17A1/MK+LRTe//NaxoDJ/PY04iY5yn8dPZxQ+4QTVve33mXVY8xG8PbFzTgFukgAnZkiV6RDDw5qztl0GpJTXIN2Cqz4qjKR263CWgfwqR7K/+ruq5ISDFS8CHxD4efkilLLuyi/6ykSncnWyyCgi80Jw4qfT2r8K8D4Mxp9eSpZn5ypgdUHkSQ/xGv4Fn8GTX4iGwqXD9mjHfE1zHn4hnb4gdAxKUT5wrCBNYEUO6xE74uv1WOtLHAI+PnTXp8Kj2B7x5zF
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-tunnel-credentials
      namespace: cloudflare-tunnel
