apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openwebui-release
  namespace: openwebui
spec:
  interval: 1m # Interval de synchronisation avec le repository
  chart:
    spec:
      chart: open-webui # Nom du chart
      version: 5.20.0  # Version du chart
      sourceRef:
        kind: HelmRepository
        name: openwebui-repository
        namespace: openwebui
  values:
    replicaCount: 1
    ingress:
      enabled: true
      class: nginx
      host: openwebui.bytedragon.tech
    pipelines:
      enabled: true
    ollama:
      enabled: false
    redis-cluster:
      enabled: false
    livenessProbe:
      httpGet:
        path: /health
        port: http
      failureThreshold: 1
      periodSeconds: 10
    readinessProbe:
      httpGet:
        path: /health/db
        port: http
      failureThreshold: 1
      periodSeconds: 10
    startupProbe:
      httpGet:
        path: /health
        port: http
      initialDelaySeconds: 30
      periodSeconds: 5
      failureThreshold: 20
    extraEnvVars:
      - name: OPENAI_API_KEY
        valueFrom:
          secretKeyRef:
            name: openwebui-secret
            key: openai-api-key
    