apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn-release
  namespace: longhorn-system
spec:
  interval: 1m
  chart:
    spec:
      chart: longhorn # Nom du chart
      version: 1.8.0  # Version du chart
      sourceRef:
        kind: HelmRepository
        name: longhorn-repository
        namespace: longhorn-system
  values:
    defaultSettings:
      deletingConfirmationFlag: true # Flag that prevents accidental uninstallation of Longhorn.
