apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: stirlingpdf-release
  namespace: stirlingpdf
spec:
  interval: 15m0s # Interval de synchronisation avec le repository
  chart:
    spec:
      chart: stirling-pdf-chart # Nom du chart
      version: 1.7.0  # Version du chart
      sourceRef:
        kind: HelmRepository
        name: stirlingpdf-repository
        namespace: stirlingpdf
  values:
    replicaCount: 1
    ingress:
      enabled: true
      annotations:
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
        external-dns.alpha.kubernetes.io/hostname: stirling.wittnerlab.com
        external-dns.alpha.kubernetes.io/target: a43b34e6-c752-44d1-99a5-cefa29a1fe53.cfargotunnel.com
      hosts:
        - name: stirling.wittnerlab.com
          path: /
    resources:
      requests:
        cpu: 5m
        memory: 400Mi  # Augmenté pour éviter les OOM