ingress:
  enabled: true
  ingressClassName: "nginx"
  hosts:
    - name: stirling.bytedragon.tech
      path: /
resources:
  limits:
    cpu: 500m  # Augmenté pour accélérer le démarrage
    memory: 512Mi  # Augmenté pour éviter les OOM
  requests:
    cpu: 100m
    memory: 256Mi
probes:
  liveness:
    initialDelaySeconds: 60
  readiness:
    initialDelaySeconds: 60