apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gha-runner-scale-set-controller-release
  namespace: arc-systems
spec:
  interval: 1m
  chart:
    spec:
      chart: gha-runner-scale-set-controller # Nom du chart
      version: 0.12.1
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller-charts-repository
        namespace: arc-systems