apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: database-minio-release
  namespace: database
spec:
  interval: 15m0s
  chart:
    spec:
      chart: minio # Nom du chart
      version: 15.0.7
      sourceRef:
        kind: HelmRepository
        name: database-minio-repository
        namespace: database
  values:
    persistence:
      size: 10Gi
    auth:
      existingSecret: database-minio-secret
      rootUserSecretKey: minio_admin_name
      rootPasswordSecretKey: minio_admin_password
    ingress:
      enabled: true
      hostname: minio-console.wittnerlab.com
      annotations:
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
        external-dns.alpha.kubernetes.io/hostname: minio-console.wittnerlab.com
        external-dns.alpha.kubernetes.io/target: a43b34e6-c752-44d1-99a5-cefa29a1fe53.cfargotunnel.com