apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: database-minio-release
  namespace: database
spec:
  interval: 1m
  chart:
    spec:
      chart: minio # Nom du chart
      version: 5.4.0
      sourceRef:
        kind: HelmRepository
        name: database-minio-repository
        namespace: database
  values:
    persistence:
      existingClaim: database-minio-pvc
    users:
      - name: minio
        existingSecret: database-minio-secret
        existingSecretKey: minio_console_password
        policy: readonly