cloudflare:
  tunnelName: "demo-lab"
  tunnelId: "da623258-6bcf-4ffb-b717-32182c6f457e"
  secretName: "tunnel-credentials"
  ingress:
    - hostname: "*.bytedragon.tech"
      service: "https://ingress-nginx-controller.kube-system.svc.cluster.local:443"
      originRequest:
        noTLSVerify: true

resources:
  limits:
    cpu: "100m"
    memory: "128Mi"
  requests:
    cpu: "100m"
    memory: "128Mi"

replicaCount: 1
