apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: database-postgres-release
  namespace: database
spec:
  interval: 1m
  chart:
    spec:
      chart: postgresql # Nom du chart
      version: 16.4.16
      sourceRef:
        kind: HelmRepository
        name: database-postgres-repository
        namespace: database
  values:
    global:
      defaultStorageClass: longhorn-static-retain
      postgresql:
        auth:
          existingSecret: database-postgres-secret
          secretKeys:
            adminPasswordKey: admin_postgres_password