apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  project: default
  sources:
    - chart: longhorn
      repoURL: https://charts.longhorn.io/
      targetRevision: v1.10.0
      helm:
        values: |
          preUpgradeChecker:
            jobEnabled: false
    - repoURL: https://github.com/jbwittner/k8s_deploy
      targetRevision: main
      path: gitops/infra/longhorn/namespace.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
