apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-longhorn
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      enabled: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - chart: longhorn
      repoURL: https://charts.longhorn.io/
      targetRevision: v1.10.0 # Replace with the Longhorn version you'd like to install or upgrade to
      helm:
        values: |
          metrics:
            serviceMonitor.enabled: true
          preUpgradeChecker:
            jobEnabled: false
      # Source pour les ressources auxiliaires (namespace, secrets, etc.)
    - repoURL: https://github.com/jbwittner/k8s_deploy
      targetRevision: main
      path: gitops/infra/longhorn/resources
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
