apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: metrics-server-repository
  namespace: metrics-server
spec:
  interval: 24h0m
  url: https://kubernetes-sigs.github.io/metrics-server