apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankwiz-app
spec:
  template:
    spec:
      containers:
        - name: bankwiz-server-container
          volumeMounts:
            - name: bankwiz-server-additional-volume
              mountPath: /app/config
      volumes:
        - name: bankwiz-server-additional-volume
          configMap:
            name: bankwiz-server-additional-config