---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: bankwiz-dev-secret
  namespace: bankwiz-dev
spec:
  encryptedData:
    bankwiz_user_postgres_password: AgBtw76YDnn7YxwsvFw+39k97zU9YPDbN6SkvatzVz4isjvoVVz2gwa3ugKqmtzqZIW9+mvbVBz0r+mmcNWh0dszyZvmUjaPUonZY0G52XN6lBxkvO9JZJOmIxW2gd6ej6IHXKFKSwzci7rmTpxetF7HTQUrHgxt7kaaLTsi4BS1reegND0iXxmad2hh/wVAa1LLRntCT1d3jOMUhXRKxd1k15oIJAUfcVGCYoyOXpYIoVFNkWGWyaTLabVAhCVvMAHlDgowTtnM2I541Sj9ufPfW4tNHbEjgL5mrNlcEJuS0FGcwfgp1Wwz2caBRI7hoVNY0O++zYc1BVH8LxfweTd/1Tvdacr3JpQUtG1YX3vvi3vQauBeFasGIBMOCXCT6FCF1CpPbAKzx5ZkpKk/DxztABRj+vj1fD4tDfq8wRAuZVs2gGtu9TJP/yXZHACZm0H5yD02GNwx6yGtmujJFzTkXfwGFFhQaCChm0Tbavdv/N7MqMDUMZ7jp4NqWAYQEFuI18TfO6INznYq0hSkxDqPn11vOAFYeUjmXCrt8GTSPoFzvZjVWZUm03HBLnVFe52856h5jYeVerQeU7h6kn02Z+dtJpfoSGmJ9L/chNM+NC2WDYzKimdkD6m4Ah+1KaYg+uXSi7WsF+RiGnN1pl5z8zo7OVDWrh/MMxB1Gmgk+y7efcsH5Eddbc15mHVyluarPhAFu+TKDuuXJsh2AKctGpc=
  template:
    metadata:
      creationTimestamp: null
      name: bankwiz-dev-secret
      namespace: bankwiz-dev
