apiVersion: apps/v1
kind: Deployment
metadata:
  name: satisfactory-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: satisfactory
  template:
    metadata:
      labels:
        app: satisfactory
    spec:
      volumes:
      - name: satisfactory-gamefiles
        persistentVolumeClaim:
          claimName: satisfactory-data-gamefiles
      - name: satisfactory-saves
        persistentVolumeClaim:
          claimName: satisfactory-data-saves
      containers:
        - name: satisfactory-container
          image: wolveix/satisfactory-server:v1.9.9
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: satisfactory-config
          resources:
            requests:
              memory: "4Gi"
              cpu: "1000m"
            limits:
              memory: "8Gi"
              cpu: "2000m"
          volumeMounts:
            - name: satisfactory-gamefiles
              mountPath: /config/gamefiles
            - name: satisfactory-saves
              mountPath: /config/gamefiles