apiVersion: v1
kind: Service
metadata:
  name: satisfactory-service
spec:
  selector:
    app: satisfactory
  type: NodePort
  ports:
    - name: tcp-7777
      nodePort: 30777
      port: 7777
      targetPort: 7777
      protocol: TCP
    - name: udp-7777
      nodePort: 30777
      port: 7777
      targetPort: 7777
      protocol: UDP
    - name: tcp-30888
      nodePort: 30888
      port: 30888
      targetPort: 30888
      protocol: TCP