---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: satisfactory-data-gamefiles
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: satisfactory-data-saves
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 5Gi