apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph-operator-release
  namespace: rook-ceph
spec:
  interval: 1m
  chart:
    spec:
      chart: rook-ceph # Nom du chart
      version: 4.12.3  # Version du chart
      sourceRef:
        kind: HelmRepository
        name: rook-ceph-repository
        namespace: rook-ceph