application:
  general:
    url: https://api-bankwiz-dev.wittnerlab.com
  db:
    host: database-postgres-release-postgresql.database.svc.cluster.local
    port: 5432
    name: bankwiz_db_dev
    user: bankwiz_user_dev
    password: ${BANKWIZ_USER_POSTGRES_PASSWORD}
  oauth2:
    issuer-uri: https://bankwiz-development.eu.auth0.com/
    audience: bankwiz_server
spring:
  jpa:
    hibernate:
      ddl-auto: validate
logging:
  level:
    root: INFO
    fr.bankwiz.server:
      application.aop: INFO
      domain.service: INFO
      infrastructure:
        spijpa: WARN
        apirest: WARN