apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bankwiz-dev
resources:
- sealed-secret.yaml
- namespace.yaml
- service-account.yaml
- ../common
images:
- name: bankwiz-server-image
  newName: ghcr.io/jbwittner/bankwiz_server
  newTag: develop-d92e34120acbe33ea8c643b5146cb6ec30b5abf9
configMapGenerator:
- name: bankwiz-server-additional-config
  files:
    - application.yaml
patches:
- path: ingress-patch.json
  target:
    kind: Ingress
    name: bankwiz-ingress
- path: additional-config.yaml
  target:
    kind: Deployment
    name: bankwiz-deployment