apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bankwiz-dev
resources:
- sealed-secret.yaml
- namespace.yaml
- service-account.yaml
- ingress.yaml
- ../common
images:
- name: bankwiz-server-image
  newName: ghcr.io/jbwittner/bankwiz_server
  newTag: develop-f5f974b6c4702e2a644251644e39e06b7255b9b1
configMapGenerator:
- name: bankwiz-server-additional-config
  files:
    - application.yaml
patches:
- path: additional-config.yaml
  target:
    kind: Deployment
    name: bankwiz-deployment