apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployment-updater
  namespace: bankwiz-dev  # Change selon ton besoin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-updater-role
  namespace: bankwiz-dev
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-updater-binding
  namespace: bankwiz-dev
subjects:
  - kind: ServiceAccount
    name: deployment-updater
    namespace: bankwiz-dev
roleRef:
  kind: Role
  name: deployment-updater-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: deployment-updater-token
  namespace: bankwiz-dev  # Change selon ton besoin
  annotations:
    kubernetes.io/service-account.name: "deployment-updater"
type: kubernetes.io/service-account-token
