apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage-release
  namespace: homepage
spec:
  interval: 1m
  chart:
    spec:
      chart: homepage # Nom du chart
      version: 2.0.1
      sourceRef:
        kind: HelmRepository
        name: homepage-repository
        namespace: homepage
  values:
    resources:
      requests:
        cpu: 30m
        memory: 150Mi
    config:
      bookmarks:
        - Gestion:
            - Ticktick:
                - abbr: TT
                  href: https://ticktick.com/
        - Developer:
            - Github:
                - abbr: GH
                  href: https://github.com/
            - Une tasse de café:
                - abbr: UTC
                  href: https://une-tasse-de.cafe/
        - IA:
            - ChatGPT:
                - abbr: CGPT
                  href: https://chat.openai.com/
            - Github Copilot:
                - abbr: GC
                  href: https://copilot.github.com/
            - Perplexity:
                - abbr: PP
                  href: https://www.perplexity.ai/
            - Mistral:
                - abbr: M
                  href: https://chat.mistral.ai/
        - Entertainment:
            - YouTube:
                - abbr: YT
                  href: https://youtube.com/
      services:
        - Monitoring:
            - Grafana:
                icon: grafana.png
                href: https://grafana.bytedragon.tech/
                description: Grafana
        - Tools:
            - Draw.io:
                icon: draw-io.png
                href: https://drawio.bytedragon.tech/
                description: Online diagram software
            - Excalidraw:
                icon: excalidraw.png
                href: https://excalidraw.bytedragon.tech/
                description: Virtual collaborative whiteboard tool
            - IT Tools:
                icon: it-tools.png
                href: https://ittools.bytedragon.tech/
                description: Handy tools for developers
            - Stirling PDF:
                icon: mdi-file-pdf-box
                href: https://stirling.bytedragon.tech/
                description: PDF manipulation tool
            - PrivateBin :
                icon: mdi-content-paste
                href: https://privatebin.bytedragon.tech/
                description: Minimalist, open source online pastebin
      widgets:
        - search:
            provider: google
            target: _blank
            focus: true
            showSearchSuggestions: true
      kubernetes:
        mode: cluster
      settings:

    # The service account is necessary to allow discovery of other services
    serviceAccount:
      create: true
      name: homepage

    # This enables the service account to access the necessary resources
    enableRbac: true

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - host: homepage.bytedragon.tech
            paths:
              - path: /
                pathType: Prefix