apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage-release
  namespace: homepage
spec:
  interval: 1m
  chart:
    spec:
      chart: homepage # Nom du chart
      version: 2.0.1
      sourceRef:
        kind: HelmRepository
        name: homepage-repository
        namespace: homepage
  values:
    resources:
      requests:
        cpu: 3m
        memory: 100Mi
    config:
      bookmarks:
        - Gestion:
            - Ticktick:
                - abbr: TT
                  href: https://ticktick.com
        - Developer:
            - Github:
                - abbr: GH
                  href: https://github.com
            - Une tasse de café:
                - abbr: UTC
                  href: https://une-tasse-de.cafe
            - Cloudflare:
                - abbr: CF
                  href: https://dash.cloudflare.com
            - Ovh:
                - abbr: OVH
                  href: https://www.ovhcloud.com
        - IA:
            - ChatGPT:
                - abbr: CGPT
                  href: https://chat.openai.com
            - Gemini:
                - abbr: GEM
                  href: https://gemini.google.com
            - Github Copilot:
                - abbr: GC
                  href: https://copilot.github.com
            - Perplexity:
                - abbr: PP
                  href: https://www.perplexity.ai
      services:
        - Monitoring:
            - Grafana:
                icon: grafana.png
                href: https://grafana.wittnerlab.com/
                description: Grafana
        - Blog:
            - LaBoussole:
                icon: cloudflare-pages.png
                href: https://laboussole.dev/
                description: Mon blog personnel
        - Tools:
            - Draw.io:
                icon: draw-io.png
                href: https://drawio.wittnerlab.tech/
                description: Online diagram software
            - Excalidraw:
                icon: excalidraw.png
                href: https://excalidraw.wittnerlab.tech/
                description: Virtual collaborative whiteboard tool
            - IT Tools:
                icon: it-tools.png
                href: https://ittools.wittnerlab.tech/
                description: Handy tools for developers
            - Stirling PDF:
                icon: mdi-file-pdf-box
                href: https://stirling.wittnerlab.tech/
                description: PDF manipulation tool
            - PrivateBin :
                icon: mdi-content-paste
                href: https://privatebin.wittnerlab.tech/
                description: Minimalist, open source online pastebin
      widgets:
        - search:
            provider: google
            target: _blank
            focus: true
            showSearchSuggestions: true
      kubernetes:
        mode: cluster
      settings:

    # The service account is necessary to allow discovery of other services
    serviceAccount:
      create: true
      name: homepage

    # This enables the service account to access the necessary resources
    enableRbac: true

    ingress:
      main:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
          external-dns.alpha.kubernetes.io/hostname: homepage.wittnerlab.com
          external-dns.alpha.kubernetes.io/target: a43b34e6-c752-44d1-99a5-cefa29a1fe53.cfargotunnel.com
        hosts:
          - host: homepage.wittnerlab.com
            paths:
              - path: /
                pathType: Prefix