apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sealed-secrets-release
  namespace: sealed-secrets
spec:
  interval: 1m
  chart:
    spec:
      chart: sealed-secrets # Nom du chart
      version: 2.17.1  # Version du chart
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets-repository
        namespace: sealed-secrets