apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sealed-secrets-release
  namespace: flux-system
spec:
  interval: 1m
  chart:
    spec:
      chart: sealed-secrets # Nom du chart
      version: 2.17.1  # Version du chart
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
      version: ">=1.15.0-0"
  releaseName: sealed-secrets-controller
  targetNamespace: flux-system
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
