apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: sealed-secrets-repository
  namespace: kube-system
spec:
  interval: 1m
  url: https://bitnami-labs.github.io/sealed-secrets