---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: database-secret
  namespace: database
spec:
  encryptedData:
    admin_postgres_password: AgB4trGpM+uBJ432+IqkM7MR64xEGUZC/lAU+E9cF7xn5cbyW1KJcH3jKx/Fo6horyT7hIZrgyBX8Ntc7IvSQfKl0oCnFqo409CVzfdlvCjWJn1eMMUOGgs3i3xBU9iA/49Cth5eAP/kENoDvrVnv5/QhtSHIzOQFpzvwhnabfJVGi9hZEbu3BMrDR77aYoPRlFvuMyNdOL0LWhoU+cfZ6Fblx3ubbVFGsnP/mh3uZUJcs2nk0fAe2V3qy4J647xZ7iaL3FgoS5zDMxvyGSUXi2Xmt1X5VjoPSbCfRF/KaZgAiPiZDmeSGn+CioKxXUTUKIoW6FjLb2p/IUsAS/064+Hc4YP1QsQbaCmpL+Y9h652PshtBG2C5E4oEks4X72p7dAqnhgs8lTeN+QsSvURahyRNqNHSsZF3udTqhh6BBqfCnFSwMcO505mSjP/JtUhvYDj1RfouHid8NWa8ycLJjNGI3PKg/BnfTCPYBwwg75gyOQ1Vf9f1H7QsbwcxQJ4WFWie88N2luwiL/i0UpQFwDpMPWj9pvOnbx5i/bJohUibgYTcBM5p4GQuqBAN2OXv0FD+KoccorbsZF3WzkWXRKckgf600sTNg3w1oNI2w1FKToJi/0vfchYx0AmBpM7ZqrBg+1UMydAQB4HPVj6l5EAKkJn8xhJ2vtuSPsOdTkp8r8bsdYO8XJDrba/LPQjFk/oWrSW/YFB9nVWrA9/10GcPM=
  template:
    metadata:
      creationTimestamp: null
      name: database-secret
      namespace: database
