apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gha-runner-scale-set-bankwiz-release
  namespace: arc-runner-set
spec:
  interval: 1m
  chart:
    spec:
      chart: gha-runner-scale-set # Nom du chart
      version: 0.12.1
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller-charts-repository
        namespace: arc-runner-set
  values:
    githubConfigUrl: https://github.com/jbwittner/bankwiz_server
    githubConfigSecret: github-bankwiz-secret
    minRunners: 5
    maxRunners: 5
    runnerScaleSetName: talos-runner
    template:
      containers:
      - name: runner-action
        image: ghcr.io/actions/actions-runner:latest
        command: ["/home/runner/run.sh"]
      - name: runner-ubuntu
        image: ghcr.io/actions/ubuntu-24.04
        command: ["/home/runner/run.sh"]
