apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gha-runner-scale-set-bankwiz-release
  namespace: arc-runner-set
spec:
  interval: 1m
  chart:
    spec:
      chart: gha-runner-scale-set # Nom du chart
      version: 0.12.1
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller-charts-repository
        namespace: arc-runner-set
  values:
    githubConfigUrl: https://github.com/jbwittner/bankwiz_server
    githubConfigSecret: github-bankwiz-secret
    minRunners: 1
    maxRunners: 10
    runnerScaleSetName: talos-runner
    template:
      spec:
        containers:
        - name: runner
          image: ghcr.io/jbwittner/action_runner_image:main-67576989a87b40018d62af800c00d38af8aaaf80
          command: ["/home/runner/run.sh"]
