apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gha-runner-scale-set-bankwiz-release
  namespace: arc-runner-set
spec:
  interval: 1m
  chart:
    spec:
      chart: gha-runner-scale-set # Nom du chart
      version: 0.12.1
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller-charts-repository
        namespace: arc-runner-set
  values:
    githubConfigUrl: https://github.com/jbwittner/bankwiz_server
    githubConfigSecret: github-bankwiz-secret
    minRunners: 1
    maxRunners: 10
    runnerScaleSetName: talos-runner
    template:
      spec:
        securityContext:
          fsGroup: 123
        containers:
        - name: runner
          image: ghcr.io/jbwittner/action_runner_image:main-e46ae4c26187615dabbc542d129cc490acffdeda
          command: ["/home/runner/run.sh"]
        #   volumeMounts:
        #   - name: maven-repository
        #     mountPath: /home/runner/.m2/repository
        # volumes:
        # - name: maven-repository
        #   ephemeral:
        #     volumeClaimTemplate:
        #       spec:
        #         accessModes: [ "ReadWriteOnce" ]
        #         resources:
        #           requests:
        #             storage: 5Gi
