apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gha-runner-scale-set-bankwiz-release
  namespace: arc-systems
spec:
  interval: 1m
  chart:
    spec:
      chart: gha-runner-scale-set # Nom du chart
      version: 0.12.1
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller-charts-repository
        namespace: arc-systems
  values:
    githubConfigUrl: https://github.com/jbwittner/bankwiz_server
    githubConfigSecret: github-bankwiz-secret
    minRunners: 0
    maxRunners: 10
    runnerScaleSetName: talos-runner
    containerMode:
      type: "dind"
      kubernetesModeWorkVolumeClaim:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "ceph-block"
        resources:
          requests:
            storage: 2Gi
    template:
      spec:
        containers:
        - name: runner
          image: ghcr.io/jbwittner/action_runner_image:main-e46ae4c26187615dabbc542d129cc490acffdeda
          command: ["/home/runner/run.sh"]
          resources:
            limits:
              cpu: "4.0"
              memory: "8Gi"
            requests:
              cpu: "2.0"
              memory: "4Gi"