apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gha-runner-scale-set-bankwiz-release
  namespace: arc-runner-set
spec:
  interval: 1m
  chart:
    spec:
      chart: gha-runner-scale-set # Nom du chart
      version: 0.12.1
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller-charts-repository
        namespace: arc-runner-set
  values:
    githubConfigUrl: https://github.com/jbwittner/bankwiz_server
    githubConfigSecret: github-bankwiz-secret
    minRunners: 0
    maxRunners: 10
    runnerScaleSetName: talos-runner
    template:
      containers:
      - name: runner-ubuntu
        image: ghcr.io/jbwittner/action_runner_image:main-f7871ebecae63190f5852384ab80a91368c78c1a
        command: ["/home/runner/run.sh"]
