---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-bankwiz-secret
  namespace: arc-systems
spec:
  encryptedData:
    github_token: AgBc4A2hrobpd0mbJNZECjLBy2vLRMX5IQcuYRqRXXoh61MADBQ0nqits7TVRyz+bPeiq56Mlo0fbbdeEmSHkBGRtYyL/uIfawNehdhkmVuM5IYqcQWuQKRTfJM+gThcjmbrNwm6IB6QFSCe2YowNr+HkDZIFtsztk2Cw9NyDNvytP60+HZV01MIqWvRePAycTP2bL9/w9nNuRFt8SyrFXe5qLl+lm0/TnX/zi1G7CMYjVw7DGWThh4dlu1mrQ2CP1110t5F2RgRjXkliZ3rYoPg43dCVIvZ0NSx1s8oqBpNJO5GoFproOLHo1G2l2OFlI0iA6QyJH44S5E94t2A4v4a2o1zvQJilet5ruMMDgqDVChmpBzh+ERIGjwCZWtqav9wabfYeEBdWf2K/xfg8/oxaueLCSU3pkM/mTPsrU4iUJy9j50JXRKpQBBpRfvuwTxXIF57o+MLU3K8f/lDr0EXp19ngznRoCJPB/5ftOEgjqcKs8TjxYeQ+KWqLk/lIx/sj1FPKiSUPQchUWC6/hwUl5myvg+Pypf/ZeD/HRm4CLIuJ7+2Idm1Q0PGPnxPC0TWB6MFQXh6tAS1GP6CfDSf1wzCio+FIZcAsDbtDF4ah5jNJcDrRk1W8wFIwZ9eF+wngKRTkriwp6rmZfVaMwEJoDnY25NDFq+tenhqWGb1o51uVN7lk0hIRr8A1BDQWxSZGR1Ub9altMEyjW3Ea/MKpjM24B3M7BnoYqPkjj5wJeMMm1Sazwhc
  template:
    metadata:
      creationTimestamp: null
      name: github-bankwiz-secret
      namespace: arc-systems
