---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-notification-flux-discord
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./flux/discord
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
