apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: pool-8
  namespace: metallb-system
spec:
  addresses:
  - 192.168.8.110-192.168.8.160
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: pool-9
  namespace: metallb-system
spec:
  addresses:
  - 192.168.9.110-192.168.9.160
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: pool-10
  namespace: metallb-system
spec:
  addresses:
  - 192.168.10.110-192.168.10.160