apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb-system  # Applique ce namespace par défaut aux ressources
resources:
  - namespace.yaml
  - metallb.yaml
  - ipaddresspool.yaml
  - l2advertisement.yaml