apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb-system  # Applique ce namespace par défaut aux ressources
resources:
  - "github.com/metallb/metallb/config/native?ref=v0.14.9"
  - ipaddresspool.yaml
  - l2advertisement.yaml