apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb-system  # Applique ce namespace par défaut aux ressources
resources:
  - namespace.yaml
  - github.com/metallb/metallb/tree/v0.14.9/config/native
  - ipaddresspool.yaml
  - l2advertisement.yaml