apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-ceph-rook-cluster
  namespace: argocd
spec:
  destination:
    namespace: rook-ceph
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: rook-ceph-cluster
    repoURL: https://charts.rook.io/release
    targetRevision: v1.18.6
    helm:
      values: |
        operatorNamespace: rook-ceph
  syncPolicy:
    syncOptions:
      - CreateNamespace=true