apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-cloudnative-pg-operator
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - chart: cnpg
      repoURL: https://cloudnative-pg.github.io/charts
      targetRevision: 0.26.1
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system
